### ISSUE TITLE
BOM

### ISSUE THREAD

**Issue by rusefillc** [zed65/ESP32display#1]
What is the exact display you've used?

What is the exact ESP32 you've used?

**Comment by zed65** [comment]
Display: 1.28" GC9A01, https://www.aliexpress.com/item/1005004911604497.html
ESP32: ESP32 WROOM 32, https://www.aliexpress.com/item/1005002674252017.html

**Comment by rusefillc** [comment]
@zed65 they have 5 options for ESP32 WROOM-32D WROOM-32U etc?

**Comment by zed65** [comment]
Mine is just ESP32 Wroom 32, no D or U.
https://www.aliexpress.com/item/1005002435072060.html

**Comment by rusefillc** [comment]
Thank you @zed65 just ordered both :)
